FROM openjdk:8u212-b04-jdk-stretch
RUN mkdir -p /srv/minecraft
WORKDIR /srv/minecraft
RUN apt-get update \
	&& apt-get -y install wget \
	&& wget https://cdn.getbukkit.org/spigot/spigot-1.14.3.jar -O spigot.jar \
	&& apt-get -y remove wget \
	&& apt-get -y autoremove --purge
RUN mkdir plugins
ADD Tutorial.jar /plugins/Tutorial.jar
CMD ["java","-Xms1024M","-Xmx2048M","-Dcom.mojang.eula.agree=true","-Dfile.encoding=UTF-8","-jar","spigot.jar","nogui"]
EXPOSE 25565
