FROM adoptopenjdk/openjdk16:armv7l-ubuntu-jdk-16.0.1_9-slim
RUN mkdir -p /srv/minecraft
WORKDIR /srv/minecraft
RUN apt-get update \
  && apt-get -y install wget \
  && wget https://papermc.io/api/v1/paper/1.17.1/109/download -O paper.jar \
  && apt-get -y remove wget \
  && apt-get -y autoremove --purge \
  && rm -rf /var/lib/apt/lists/*
CMD ["java","-Xms512M","-Xmx2048M","-Dcom.mojang.eula.agree=true","-Dfile.encoding=UTF-8","-jar","paper.jar","nogui"]
EXPOSE 25565
