FROM openjdk:8u212-b04-jdk-stretch
RUN mkdir -p /srv/minecraft
WORKDIR /srv/minecraft
RUN apt-get update \
  && apt-get -y install wget \
  && wget https://papermc.io/api/v1/paper/1.16.5/778/download -O paper.jar \
  && apt-get -y remove wget \
  && apt-get -y autoremove --purge
CMD ["java","-Xms512M","-Xmx2048M","-Dcom.mojang.eula.agree=true","-Dfile.encoding=UTF-8","-jar","paper.jar","nogui"]
EXPOSE 25565
