FROM adoptopenjdk/openjdk16:armv7l-ubuntu-jdk-16.0.1_9-slim
RUN mkdir -p /srv/waterfall
WORKDIR /srv/waterfall
RUN apt-get update \
  && apt-get -y install wget \
  && wget https://papermc.io/api/v1/waterfall/1.17/445/download -O waterfall.jar \
  && apt-get -y remove wget \
  && apt-get -y autoremove --purge
CMD ["java","-Xms512M","-Xmx2048M","-jar","waterfall.jar"]
EXPOSE 25577
