name: build our image

on:
  push:
    paths:
      - server/**
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin
      - name: Determine version to build
        id: version
        run: |
          LATEST_VERSION=$(just get-latest-server-version marcstreeter/spigot)
          NEW_VERSION=$(just increment-version $LATEST_VERSION)
          echo "Latest version: $LATEST_VERSION"
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the server image
        working-directory: ./server
        run: |
          docker buildx build \
            --push \
            --tag marcstreeter/spigot:latest \
            --tag marcstreeter/spigot:${{ steps.version.outputs.new_version }} \
            --platform linux/amd64,linux/arm64 .
      - name: Verify published version and update manifests
        run: |
          PUBLISHED_VERSION=$(just get-latest-server-version marcstreeter/spigot)
          echo "Setting K8s manifests reference for marcstreeter/spigot to most recent published version: $PUBLISHED_VERSION"
          
          # Update all server K8s manifests
          sed -i "s|image: marcstreeter/spigot:.*|image: marcstreeter/spigot:$PUBLISHED_VERSION|g" kubernetes/deploy-world.yml
          sed -i "s|image: marcstreeter/spigot:.*|image: marcstreeter/spigot:$PUBLISHED_VERSION|g" kubernetes/deploy-world-berry.yml
          sed -i "s|image: marcstreeter/spigot:.*|image: marcstreeter/spigot:$PUBLISHED_VERSION|g" kubernetes/deploy-world-ice.yml
          sed -i "s|image: marcstreeter/spigot:.*|image: marcstreeter/spigot:$PUBLISHED_VERSION|g" kubernetes/deploy-world-lily.yml
          sed -i "s|image: marcstreeter/spigot:.*|image: marcstreeter/spigot:$PUBLISHED_VERSION|g" kubernetes/deploy-world-sand.yml
          sed -i "s|image: marcstreeter/spigot:.*|image: marcstreeter/spigot:$PUBLISHED_VERSION|g" kubernetes/deploy-world-wood.yml
          
          # Pull latest changes to avoid conflicts
          git pull origin master
          
          # Commit changes
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add kubernetes/deploy-world*.yml
          git commit -m "Update server image to $PUBLISHED_VERSION"
          git push
