name: build our image

on:
  push:
    paths:
      - util/**
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the utils image
        working-directory: ./util
        run: |
          docker buildx build \
            --push \
            --tag marcstreeter/utils:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
